version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: aprs
      MONGO_INITDB_ROOT_PASSWORD: aprs
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
    networks:
      - dev

networks:
 dev:
   name: dev
   driver: bridge